# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='images',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
