# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-01 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='images',
            new_name='image',
        ),
    ]
