# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_sourse_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sourse_org',
            new_name='course_org',
        ),
    ]
