# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180304_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
