# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
